# Ansible
ansible_python_interpreter: "auto_silent"

# Paths
bashrc: "{{ lookup('env','HOME') }}/.bashrc"
dot_files: "{{ lookup('env','PWD') }}"
home: "{{ lookup('env','HOME') }}"

# Git
git:
  name: ""
  email: ""
  gpg: ""

# ASDF
asdf:
  path: "{{ lookup('env','HOME') }}/.asdf"
  execute_command: ". {{ lookup('env','HOME') }}/.asdf/asdf.sh"
  version: "v0.8.1"
  shell: "bash"
