ansible_python_interpreter: "auto_silent"

home: "{{ lookup('env','HOME') }}"

zig_version: "0.13"
jetbrains_mono_nerd_font_version: "2.1.0"

zinit_home: "{{ lookup('env', 'XDG_DATA_HOME') | default(lookup('env', 'HOME') + '/.local/share', true) }}/zinit/zinit.git"
