ansible_python_interpreter: "auto_silent"

home: "{{ lookup('env','HOME') }}"

git:
  name: ""
  email: ""
  gpg: ""

asdf:
  path: "{{ lookup('env','HOME') }}/.asdf"
  run: ". {{ lookup('env','HOME') }}/.asdf/asdf.sh"
  version: "v0.8.1"
  shell: "bash"
