# Ansible
ansible_python_interpreter: "auto_silent"

# ASDF
asdf_path: "{{ home }}/.asdf"
asdf_run: ". {{ home }}/.asdf/asdf.sh"
asdf_shell: "bash"
asdf_version: "v0.11.3"

# Git
git_email: "rezendepauloeduardo@outlook.com"
git_gpg: "671C1CC571E4323E"
git_name: "Paulo Eduardo Rezende"

# General Variables
home: "{{ lookup('env','HOME') }}"
user: "{{ lookup('env','USER') }}"

# Visual Studio Code
visual_studio_code_build: "stable"
visual_studio_code_download_dir: "{{ x_ansible_download_dir | lookup('env','HOME') + '/.ansible/tmp/downloads') }}"
visual_studio_code_mirror: "https://packages.microsoft.com"
visual_studio_code_package: "{{ (visual_studio_code_build == 'insiders') | ternary('code-insiders', 'code') }}"
visual_studio_code_version: ""
visual_studio_code_extensions:
  - EditorConfig.EditorConfig
  - Equinusocio.vsc-community-material-theme
  - Equinusocio.vsc-material-theme
  - GitHub.copilot
  - GitHub.vscode-pull-request-github
  - IBM.output-colorizer
  - IronGeek.vscode-env
  - PKief.material-icon-theme
  - Tyriar.sort-lines
  - VisualStudioExptTeam.intellicode-api-usage-examples
  - VisualStudioExptTeam.vscodeintellicode
  - WallabyJs.quokka-vscode
  - adpyke.codesnap
  - bradlc.vscode-tailwindcss
  - dbaeumer.vscode-eslint
  - dsznajder.es7-react-js-snippets
  - eamodio.gitlens
  - equinusocio.vsc-material-theme-icons
  - esbenp.prettier-vscode
  - miguelsolorio.fluent-icons
  - ms-azuretools.vscode-docker
  - ms-vsliveshare.vsliveshare
  - msjsdiag.vscode-react-native
  - nicoespeon.abracadabra
  - redhat.vscode-yaml
  - ritwickdey.LiveServer
  - wesbos.theme-cobalt2
  - yzhang.markdown-all-in-one
