shell = "zsh"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"

[plugins.libraries]
github = "ohmyzsh/ohmyzsh"
dir = "lib"
use = ["history.zsh", "theme-and-appearance.zsh"]

[plugins.plugins]
github = "ohmyzsh/ohmyzsh"
dir = "plugins"
use = ["git.plugin.zsh", "fzf.plugin.zsh", "nvm.plugin.zsh"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]

[plugins.powerlevel10k]
github = 'romkatv/powerlevel10k'
