---
git_version: "latest"
git_delta_version: "0.16.5"
lazygit_version: "0.40.2"

git_config_file: "{{ ansible_env.HOME }}/.gitconfig"

lazygit_config_dir_darwin: "{{ ansible_env.HOME }}/Library/Application Support/lazygit"
lazygit_config_dir_debian: "{{ ansible_env.HOME }}/.config/lazygit"
lazygit_config_file: "config.yml"

git_config_core_editor: "nvim"
git_config_core_autocrlf: "input"
git_config_init_defaultbranch: "main"
git_config_pull_rebase: "false"
git_config_push_default: "current"

git_diff_tool: "diff-so-fancy"

git_aliases:
  - { name: "co", command: "checkout" }
  - { name: "br", command: "branch" }
  - { name: "ci", command: "commit" }
  - { name: "st", command: "status" }
  - { name: "unstage", command: "reset HEAD --" }
  - { name: "last", command: "log -1 HEAD" }
  - { name: "lg", command: "log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit" }
  - { name: "amend", command: "commit --amend" }
  - { name: "staged", command: "diff --staged" }
