---
- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: darwin.yml
  when: ansible_os_family == "Darwin"

- name: retrieve shell executable location
  command: which fish
  register: fish

- name: install fish plugins
  shell:
    cmd: fisher install "{{ item }}"
    executable: "{{ fish.stdout }}"
  with_items:
    - jorgebucaran/nvm.fish
    - jethrokuan/z
    - PatrickF1/fzf.fish
    - meaningful-ooo/sponge
    - IlanCosman/tide@v5
    - laughedelic/pisces

- name: add settings
  template:
    src: "config.j2"
    dest: "{{ home }}/.config/fish/config.fish"
    backup: true

- name: add fish shell as standard shell
  become: true
  lineinfile:
    path: /etc/shells
    line: "{{ fish.stdout }}"
    create: yes

- name: make fish the default shell
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: "{{ fish.stdout }}"
