---
neovim_debian_dependencies:
  - build-essential
  - curl
  - libtool
  - libtool-bin
  - autoconf
  - automake
  - cmake
  - g++
  - pkg-config
  - unzip
  - gettext

neovim_config_dir: "{{ ansible_env.HOME }}/.config/nvim"
neovim_scripts_dir: "{{ neovim_config_dir }}/scripts"
neovim_stop_daemon_script: "{{ neovim_scripts_dir }}/stop-nvim-daemons.sh"

neovim_backup_random_number: "{{ 100000 | random | int | abs }}"
neovim_backup_date_format: "{{ ansible_date_time.date }}@{{ '%02d' | format(ansible_date_time.hour|int) }}:{{ '%02d' | format(ansible_date_time.minute|int) }}:{{ '%02d' | format(ansible_date_time.second|int) }}"
neovim_backup_dir_format: "nvim.{{ neovim_backup_random_number }}.{{ neovim_backup_date_format }}~" 
