---
- name: Configure development environment
  hosts: environment
  roles:
    - role: dconf
      when: ansible_os_family == "Debian"
    
    - role: asdf
      where: ansible_os_family == "Debian"

    - role: kitty
      where: ansible_os_family == "Debian"

    - role: fonts
    - role: git
    - role: fzf
    - role: node
    - role: tmux
    - role: neovim
    - role: vscode
    - role: zsh
    - role: docker
