---
- name: Configure development environment
  hosts: environment
  roles:
    - { role: git, tags: ['git'] }
    - { role: asdf, tags: ['asdf'] }
    - { role: onepassword, tags: ['onepassword'] }
    - { role: fzf, tags: ['fzf'] }
    - { role: neovim, tags: ['neovim'] }
    - { role: node, tags: ['node'] }
    - { role: tmux, tags: ['tmux'] }
    - { role: zsh, tags: ['zsh'] }
    - { role: kitty, tags: ['kitty'] }
    - { role: vscode, tags: ['vscode'] }
