---
- name: Configure system
  hosts: localhost
  connection: local
  vars_files:
    - group_vars/all.yml
    - group_vars/vault.yml
  roles:
    - { role: system, tags: system }
    - { role: fonts, tags: fonts }
    - { role: asdf, tags: asdf }
    - { role: gpg, tags: gpg }
    - { role: git, tags: git }
    - { role: fzf, tags: fzf }
    - { role: bat, tags: bat }
    - { role: ghostty, tags: ghostty }
    - { role: neovim, tags: neovim }
    - { role: node, tags: node }
    - { role: one-password, tags: one-password }
    - { role: tmux, tags: tmux }
    - { role: visual-studio-code, tags: visual-studio-code }
    - { role: zsh, tags: zsh }
