---
- name: install vs code
  homebrew_cask:
    name: visual-studio-{{ visual_studio_code_package }}
    state: present

- name: create code folder if not exists
  file:
    path: "{{ home }}/.config/Code/User"
    state: directory

- name: add settings
  template:
    src: "settings.j2"
    dest: "{{ home }}/Library/Application Support/Code/User/settings.json"
    backup: true

- name: install extensions
  command: "'/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code' --install-extension {{ item }}"
  with_items: "{{ visual_studio_code_extensions }}"
