---
- name: install dependencies
  become: true
  apt:
    name:
      - ca-certificates
      - apt-transport-https
      - gconf2
      - libasound2
      - libgtk2.0-0
      - libxss1
      - libxcb-dri3-0
      - libdrm2
      - libgbm1
      - libxshmfence1
    state: present
    lock_timeout: 300

- name: add repository key
  become: true
  apt_key:
    url: '{{ visual_studio_code_mirror }}/keys/microsoft.asc'

- name: add repository
  become: true
  apt_repository:
    repo: 'deb [arch=amd64] {{ visual_studio_code_mirror }}/repos/code stable main'
    filename: vscode

- name: install vs code
  become: true
  apt:
    name: "{{ visual_studio_code_package }}{{ (visual_studio_code_version | length > 0) | ternary('=' + visual_studio_code_version, '') }}"
    lock_timeout: 300

- name: create code folder if not exists
  file:
    path: "{{ home }}/.config/Code/User"
    state: directory

- name: add settings
  template:
    src: "settings.j2"
    dest: "{{ home }}/.config/Code/User/settings.json"
    backup: yes

- name: install extensions
  command: "code --install-extension {{ item }}"
  with_items: "{{ visual_studio_code_extensions }}"
