---
- name: Install dependencies
  become: true
  apt:
    name:
      - ca-certificates
      - apt-transport-https
      - gconf2
      - libasound2
      - libgtk2.0-0
      - libxss1
      - libxcb-dri3-0
      - libdrm2
      - libgbm1
      - libxshmfence1
    state: present

- name: Add repository key
  become: true
  apt_key:
    url: '{{ visual_studio_code_mirror }}/keys/microsoft.asc'

- name: Add repository
  become: true
  apt_repository:
    repo: 'deb [arch=amd64] {{ visual_studio_code_mirror }}/repos/code stable main'
    filename: vscode

- name: Install VS Code
  become: true
  apt:
    name: "{{ visual_studio_code_package }}{{ (visual_studio_code_version | length > 0) | ternary('=' + visual_studio_code_version, '') }}"

- name: Create Code folder if not exists
  file:
    path: "{{ home }}/.config/Code/User"
    state: directory

- name: Add settings
  template:
    src: "settings.j2"
    dest: "{{ home }}/.config/Code/User/settings.json"
    backup: yes

- name: Install extensions
  command: "code --install-extension {{ item }}"
  with_items:
    - adpyke.codesnap
    - bradlc.vscode-tailwindcss
    - dbaeumer.vscode-eslint
    - dsznajder.es7-react-js-snippets
    - eamodio.gitlens
    - EditorConfig.EditorConfig
    - esbenp.prettier-vscode
    - GitHub.vscode-pull-request-github
    - IBM.output-colorizer
    - IronGeek.vscode-env
    - ms-azuretools.vscode-docker
    - ms-vsliveshare.vsliveshare
    - ms-vsliveshare.vsliveshare-audio
    - msjsdiag.vscode-react-native
    - nicoespeon.abracadabra
    - PKief.material-icon-theme
    - redhat.vscode-yaml
    - Tyriar.sort-lines
    - VisualStudioExptTeam.vscodeintellicode
    - WallabyJs.quokka-vscode
    - wesbos.theme-cobalt2
    - yzhang.markdown-all-in-one
