---
- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Create Code folder if not exists
  file:
    path: "{{ home }}/.config/Code/User"
    state: directory

- name: Add settings
  copy:
    src: "{{ role_path }}/files/settings.json"
    dest: "{{ home }}/.config/Code/User/settings.json"
    backup: true

- name: Install extensions
  command: "code --install-extension {{ item }}"
  with_items:
    - adpyke.codesnap
    - bradlc.vscode-tailwindcss
    - dbaeumer.vscode-eslint
    - dsznajder.es7-react-js-snippets
    - eamodio.gitlens
    - EditorConfig.EditorConfig
    - esbenp.prettier-vscode
    - GitHub.vscode-pull-request-github
    - IBM.output-colorizer
    - IronGeek.vscode-env
    - ms-azuretools.vscode-docker
    - ms-vsliveshare.vsliveshare
    - ms-vsliveshare.vsliveshare-audio
    - msjsdiag.vscode-react-native
    - nicoespeon.abracadabra
    - PKief.material-icon-theme
    - redhat.vscode-yaml
    - Tyriar.sort-lines
    - VisualStudioExptTeam.vscodeintellicode
    - WallabyJs.quokka-vscode
    - wesbos.theme-cobalt2
    - yzhang.markdown-all-in-one
