---
- name: Checking if there is any existing configuration
  stat: 
    path: "{{ home }}/.ssh"
  register: folder

- name: Backing up if there is already a configuration
  command: "mv {{ home }}/.ssh {{ home }}/.ssh-{{ ansible_date_time.iso8601 }}"
  when: folder.stat.exists

- name: Creating root folder
  file:
    path: "{{ home }}/.ssh"
    state: directory

- name: Adding settings
  copy:
    src: "{{ role_path }}/files/{{ item.file }}"
    dest: "{{ home }}/.ssh/{{ item.file }}"
  loop:
    - { file: "config" }

- name: Adding GitHub SSH private key
  copy:
    dest: '{{ home }}/.ssh/id_ed25519_github'
    content: "-----BEGIN OPENSSH PRIVATE KEY-----\n{{ lookup('onepassword', 'GitHub', field='private', subdomain=op.subdomain, master_password=op.password, username=op.email, secret_key=op.secret) | replace(' ', '\n') }}\n-----END OPENSSH PRIVATE KEY-----\n"
    mode: 0600

- name: Adding GitHub SSH public key
  copy:
    dest: '{{ home }}/.ssh/id_ed25519_github.pub'
    content: "{{ lookup('onepassword', 'GitHub', field='public', subdomain=op.subdomain, master_password=op.password, username=op.email, secret_key=op.secret) }}\n"
    mode: 0640

- name: Evaluating the authentication agent
  shell: eval "$(ssh-agent)"

- name: Adding GitHub SSH on agent
  shell: ssh-add ~/.ssh/id_ed25519_github
