---
- name: Install ASDF prerequisites
  homebrew:
    name:
      - git
      - curl
      - gpg
      - coreutils
    state: present

- name: Clone ASDF repository
  git:
    repo: "https://github.com/asdf-vm/asdf.git"
    dest: "{{ asdf_install_dir }}"
    version: "{{ asdf_version }}"
    clone: true

- name: Add ASDF initialization to shell config
  lineinfile:
    path: "{{ asdf_shell_config }}"
    line: 'source {{ asdf_install_dir }}/asdf.sh'
    create: true
    state: present

- name: Add ASDF shims to PATH
  lineinfile:
    path: "{{ asdf_shell_config }}"
    line: 'export PATH="{{ asdf_install_dir }}/shims:$PATH"'
    create: true
    state: present

- name: Configure ASDF completions for Bash
  lineinfile:
    path: "{{ asdf_shell_config }}"
    line: '. {{ asdf_install_dir }}/completions/asdf.bash'
    create: true
    state: present
  when: asdf_shell_config | regex_search('bash')

- name: Configure ASDF completions for ZSH
  lineinfile:
    path: "{{ asdf_shell_config }}"
    line: '. {{ asdf_install_dir }}/completions/asdf.zsh'
    create: true
    state: present
  when: asdf_shell_config | regex_search('zsh')

- name: Source shell configuration
  shell: source "{{ asdf_shell_config }}"
  args:
    executable: /bin/zsh
  changed_when: false
  check_mode: no
  when: asdf_shell_config | regex_search('zsh') 
