---
- name: Install dependencies
  become: true
  apt:
    name:
      - unzip
      - git
      - curl
      - autoconf
      - automake
      - gcc
      - g++
      - make
      - patch
      - pkg-config
      - binutils
      - libtool
      - bison
      - libreadline-dev
      - python-is-python3
    install_recommends: no
    cache_valid_time: 86400
  retries: 5
  register: dependencies_result
  until: dependencies_result is succeeded
