- name: Install
  git:
    repo: "https://github.com/asdf-vm/asdf.git"
    dest: "{{ home }}/.asdf"
    version: v0.8.1

- name: Source asdf
  template:
    src: "asdf.j2"
    dest: "/etc/profile.d/asdf.sh"
    owner: "root"
    group: "root"
    mode: 0755
  become: true
