---
- name: Downloading
  git:
    repo: "https://github.com/asdf-vm/asdf.git"
    dest: "{{ home }}/.asdf"
    version: "{{ asdf.version }}"
    force: true

- name: Checking if the .bashrc file exists
  stat:
    path: "{{ home }}/.bashrc"
  register: output

- name: Creating .bashrc file if it doesn't exist
  file:
    path: "{{ home }}/.bashrc"
    state: touch
  when: not output.stat.exists

- name: Loading asdf into .bashrc
  blockinfile:
    dest: "{{ home }}/.bashrc"
    marker: "# {mark} :: ANSIBLE MANAGED BLOCK :: {{ role_name }}"
    block: |
      if [ -e "$HOME/.asdf/asdf.sh" ]; then
        source $HOME/.asdf/asdf.sh
        source $HOME/.asdf/completions/asdf.bash
      fi
