---
- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Install
  git:
    repo: "https://github.com/asdf-vm/asdf.git"
    dest: "{{ asdf_path }}"
    version: "{{ asdf_version }}"

- name: Source
  become: true
  template:
    src: "asdf.j2"
    dest: "/etc/profile.d/asdf.sh"
    owner: "root"
    group: "root"
    mode: 0755
