---
- name: Install dependencies
  homebrew:
    name: 
      - zsh
      - sheldon
    state: latest

- name: Create root folder if not exists
  file:
    path: "{{ home }}/.sheldon"
    state: directory

- name: Update zsh current settings
  template:
    src: "zshrc.j2"
    dest: "{{ home }}/.zshrc"
    backup: yes

- name: Update sheldon current settings
  copy:
    src: "{{ role_path }}/files/plugins.toml"
    dest: "{{ home }}/.sheldon/plugins.toml"
    backup: true
