---
- name: Install dependencies
  homebrew:
    name: 
      - zsh
      - sheldon
    state: latest

- name: Create root folder if not exists
  file:
    path: "{{ home }}/.sheldon"
    state: directory

- name: Update current settings
  copy:
    src: "{{ role_path }}/files/{{ item.file }}"
    dest: "{{ item.path }}/{{ item.file }}"
    backup: true
  loop:
    - { file: ".zshrc", path: "{{ home }}/" }
    - { file: "plugins.toml", path: "{{ home }}/.sheldon/" }
