---
- name: Install packages
  apt:
    name: zsh
    state: present

- name: Install zoxide
  shell: "curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh"
  args:
    executable: /bin/bash
