---
- name: Install dependencies
  become: true
  apt:
    name: zsh
    state: latest

- name: Install zplug
  git:
    repo: "https://github.com/zplug/zplug.git"
    dest: "{{ home }}/.zplug"
    force: true
