---
- name: Install dependencies
  become: true
  apt:
    name: zsh
    state: latest

- name: Install sheldon
  shell: curl --proto '=https' -fLsS https://rossmacarthur.github.io/install/crate.sh | bash -s -- --repo rossmacarthur/sheldon --to ~/.local/bin
  args:
    warn: false
  ignore_errors: true

- name: Create root folder if not exists
  file:
    path: "{{ home }}/.config/sheldon"
    state: directory

- name: Update zsh current settings
  template:
    src: "zshrc.j2"
    dest: "{{ home }}/.zshrc"
    backup: yes

- name: Update sheldon current settings
  copy:
    src: "{{ role_path }}/files/plugins.toml"
    dest: "{{ home }}/.config/sheldon/plugins.toml"
    backup: true
