---
- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Install zplug
  git:
    repo: "https://github.com/zplug/zplug.git"
    dest: "{{ home }}/.zplug"
    force: true

- name: Update current settings
  copy:
    src: "{{ role_path }}/files/zshrc"
    dest: "{{ home }}/.zshrc"
    backup: true

- name: Setting zsh as default shell
  become: true
  command: "bash -lc 'chsh -s $(which zsh)'"
