---
- name: Install dependencies
  homebrew:
    name: 
      - zsh
      - zplug
    state: latest

- name: Update current settings
  template:
    src: "zshrc.j2"
    dest: "{{ home }}/.zshrc"
    backup: yes

- name: Set zsh as default shell
  become: true
  shell: "bash -lc 'chsh -s $(which zsh)'"
