---
- name: Install zsh and related tools on macOS
  include_tasks: darwin.yml
  when: ansible_os_family == 'Darwin'

- name: Install zsh and related tools on Debian
  include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Install zoxide plugin
  include_tasks: "{{ playbook_dir }}/roles/asdf/tasks/manage-plugin.yml"
  vars:
    plugin_name: "zoxide"
    plugin_version: "0.9.7"
    plugin_global: true

- name: Add zsh to /etc/shells if not already present
  lineinfile:
    path: /etc/shells
    line: /opt/homebrew/bin/zsh
    state: present
  become: true

- name: Set zsh as the default shell
  user:
    name: "{{ ansible_user_id }}"
    shell: /opt/homebrew/bin/zsh
  become: true

- name: Clone zinit repository
  git:
    repo: https://github.com/zdharma-continuum/zinit.git
    dest: "{{ zinit_home }}"
    clone: true
    update: true
    force: true

- name: Copy .zshrc template to user's home directory
  template:
    src: "zshrc.j2"
    dest: "{{ ansible_env.HOME }}/.zshrc"
    mode: 0644
    backup: true

- name: Copy .p10k.zsh template to user's home directory
  template:
    src: "p10k.j2"
    dest: "{{ ansible_env.HOME }}/.p10k.zsh"
    mode: 0644
    backup: true
