---
- name: install
  shell: curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin launch=n

- name: create symbolic link
  become: true
  file:
    src: "{{ home }}/.local/kitty.app/bin/kitty"
    dest: "/usr/bin/kitty"
    state: link

- name: create desktop entry
  copy:
    src: "{{ home }}/.local/kitty.app/share/applications/kitty.desktop"
    dest: "{{ home }}/.local/share/applications/kitty.desktop"

- name: update icon on desktop entry
  replace:
    path: "{{ home }}/.local/share/applications/kitty.desktop"
    regexp: "(?<=Icon=).*$"
    replace: "{{ home }}/.local/kitty.app/share/icons/hicolor/256x256/apps/kitty.png"
