---
- name: Install
  shell: curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin launch=n
  args:
    warn: false

- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Create root folder if not exists
  file:
    path: "{{ home }}/.config/kitty"
    state: directory

- name: Update current settings
  copy:
    src: "{{ role_path }}/files/kitty.conf"
    dest: "{{ home }}/.config/kitty/kitty.conf"
    backup: true
