---
- name: Install
  shell: curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
  args:
    warn: false

- import_tasks: pop_os.yml
  when: ansible_os_family == "Pop!_OS"

- name: Checking if there is any existing configuration
  stat: 
    path: "{{ home }}/.config/kitty/kitty.config"
  register: kitty

- name: Backing up if there is already a configuration
  command: "mv {{ home }}/.config/kitty/kitty.config {{ home }}/.config/kitty/kitty-{{ ansible_date_time.iso8601 }}"
  when: kitty.stat.exists

- name: Creating root folder
  file:
    path: "{{ home }}/.config/kitty"
    state: directory

- name: Adding settings
  copy:
    src: "{{ role_path }}/files/{{ item.file }}"
    dest: "{{ home }}/.config/kitty/{{ item.file }}"
  loop:
    - { file: "kitty.conf" }
