---
- name: Download Homebrew install script
  get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
    dest: /tmp/install_homebrew.sh
    mode: 0755

- name: Run Homebrew install script
  shell: /bin/bash /tmp/install_homebrew.sh
  args:
    creates: /opt/homebrew/bin/brew

- name: Ensure ~/.bash_profile exists
  file:
    path: "{{ home }}/.bash_profile"
    state: touch
  become: true

- name: Add Homebrew to PATH in ~/.bash_profile
  lineinfile:
    path: "{{ home }}/.bash_profile"
    line: 'eval "$(homebrew/bin/brew shellenv)"'
    insertafter: EOF
    state: present
  become: true

- name: Source ~/.bash_profile
  shell: "source {{ home }}/.bash_profile"
  args:
    executable: /bin/bash
