---
- name: Download Homebrew install script
  get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
    dest: /tmp/install_homebrew.sh
    mode: 0755

- name: Run Homebrew install script
  shell: /bin/bash /tmp/install_homebrew.sh
  args:
    creates: /opt/homebrew/bin/brew

- name: Ensure ~/.zprofile exists
  file:
    path: "{{ home }}/.zprofile"
    state: touch
  become: true

- name: Add Homebrew to PATH in ~/.zprofile
  lineinfile:
    path: "{{ home }}/.zprofile"
    line: 'eval "$(/opt/homebrew/bin/brew shellenv)"'
    insertafter: EOF
    state: present
  become: true

- name: Source ~/.zprofile
  shell: "source {{ home }}/.zprofile"
  args:
    executable: /bin/zsh
