---
- name: define variables
  set_fact:
    plugins:
      - name: "fzf"
        versions: ["0.30.0"]
        global: "0.30.0"

- name: install dependencies
  become: true
  apt:
    name:
      - fd-find
      - bat
    state: latest

- import_role:
    name: asdf
    tasks_from: add
  vars:
    plugins: "{{ plugins }}"

- import_role:
    name: asdf
    tasks_from: install
  vars:
    plugins: "{{ plugins }}"

- import_role:
    name: asdf
    tasks_from: global
  vars:
    plugins: "{{ plugins }}"
