---
- name: Set asdf plugin variables
  set_fact:
    plugin_name: fzf
    plugin_version: 0.52.1

- name: Add plugin
  include_tasks: "{{ playbook_dir }}/roles/common/tasks/asdf/add-plugin.yml"

- name: Install plugin
  include_tasks: "{{ playbook_dir }}/roles/common/tasks/asdf/install-plugin.yml"

- name: Set global plugin version
  include_tasks: "{{ playbook_dir }}/roles/common/tasks/asdf/global-plugin.yml"
