---
- name: define variables
  set_fact:
    plugins:
      - name: "fzf"
        versions: ["0.30.0"]
        global: "0.30.0"

- import_tasks: "{{ playbook_dir }}/roles/asdf/tasks/plugin/add.yml"
  vars:
    plugins: "{{ plugins }}"

- import_tasks: "{{ playbook_dir }}/roles/asdf/tasks/plugin/install.yml"
  vars:
    plugins: "{{ plugins }}"

- import_tasks: "{{ playbook_dir }}/roles/asdf/tasks/plugin/global.yml"
  vars:
    plugins: "{{ plugins }}"
