---
- import_tasks: "{{ playbook_dir }}/roles/asdf/tasks/plugin/add.yml"
  vars:
    plugins: "{{ plugins }}"

- import_tasks: "{{ playbook_dir }}/roles/asdf/tasks/plugin/install.yml"
  vars:
    plugins: "{{ plugins }}"

- import_tasks: "{{ playbook_dir }}/roles/asdf/tasks/plugin/global.yml"
  vars:
    plugins: "{{ plugins }}"

- name: Get install path
  command: "bash -lc 'asdf where {{ item.name }}'"
  args:
    chdir: "{{ asdf_path }}"
  with_items: "{{ plugins }}"
  register: output

- name: Run install script
  command: "{{ output.results[0].stdout }}/install --key-bindings --completion --no-update-rc"
