---
- name: Add
  command: "bash -lc 'asdf plugin add {{ item.name }} {{ item.repository | default() }}'"
  args:
    creates: "{{ asdf_path }}/plugins/{{ item.name }}"
    chdir: "{{ asdf_path }}"
  with_items: "{{ plugins }}"
  when: plugins | length > 0
  become: true
  become_user: root
  ignore_errors: true

- name: Install
  command: "bash -lc 'asdf install {{ item.0.name }} {{ item.1 }}'"
  args:
    creates: "{{ asdf_path }}/installs/{{ item.0.name }}/{{ item.1 }}"
    chdir: "{{ asdf_path }}"
  with_subelements:
    - "{{ plugins }}"
    - versions
    - flags:
      skip_missing: true
  when: plugins | length > 0
  become: true
  become_user: root

- name: Set global
  command: "bash -lc 'asdf global {{ item.name }} {{ item.global | default(item.versions | difference(item.delete_versions|default([])) | sort | first) }}'"
  args:
    chdir: "{{ asdf_path }}"
  when: item.versions is defined
  with_items: "{{ plugins }}"
  become: true
  become_user: root

- name: Get install path
  command: "bash -lc 'asdf where {{ item.name }}'"
  args:
    chdir: "{{ asdf_path }}"
  with_items: "{{ plugins }}"
  become: true
  become_user: root
  register: output

- name: Run install script
  command: "{{ output.results[0].stdout }}/install --key-bindings --completion --no-update-rc"
