---
- name: install dependencies
  homebrew:
    name:
      - git 
      - diff-so-fancy
      - lazygit
    state: latest

- name: update current lazygit settings
  template:
    src: "lazygit.j2"
    dest: "{{ home }}/Library/Application Support/lazygit/config.yml"
    backup: true
