---
- name: Update apt cache
  apt:
    update_cache: true

- name: Install Git
  apt:
    name: git
    state: present

- name: Install diff-so-fancy
  apt:
    name: diff-so-fancy
    state: present

- name: Download and extract Lazygit
  unarchive:
    src: "https://github.com/jesseduffield/lazygit/releases/download/v{{ lazygit_version }}/lazygit_{{ lazygit_version }}_Linux_x86_64.tar.gz"
    dest: "/usr/local/bin"
    exclude: ["LICENSE", "README.md"]
    remote_src: true
  register: lazygit_extraction

- name: Ensure Lazygit extraction was successful
  fail:
    msg: "Failed to extract Lazygit"
  when: lazygit_extraction|failed

- name: Ensure Lazygit directory exists
  file:
    path: "{{ home }}/.config/lazygit"
    state: directory
    mode: 0755

- name: Set permissions for Lazygit executable
  file:
    path: "/usr/local/bin/lazygit"
    mode: 0755

- name: Copy Lazygit config template to user's home directory
  template:
    src: "{{ role_path }}/files/lazygit_config.j2"
    dest: "{{ home }}/.config/lazygit/config.yml"
    mode: 0644
    backup: true
