---
- name: Add diff-so-fancy repository
  become: true
  apt_repository:
    repo: ppa:aos1/diff-so-fancy
    codename: focal
    update_cache: true

- name: Install dependencies
  become: true
  apt:
    name:
      - git
      - diff-so-fancy
    state: latest
