---
- name: define variables
  set_fact:
    version: "v0.38.2"

- name: add diff-so-fancy repository
  become: true
  apt_repository:
    repo: ppa:aos1/diff-so-fancy
    codename: jammy

- name: install dependencies
  become: true
  apt:
    name:
      - git
      - diff-so-fancy
    state: latest

- name: install lazygit
  become: true
  unarchive:
    src: "https://github.com/jesseduffield/lazygit/releases/download/{{ version }}/lazygit_{{ version | replace('v', '') }}_Linux_x86_64.tar.gz"
    dest: "/usr/local/bin"
    exclude: ["LICENSE", "README.md"]
    remote_src: true
