---
- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- import_tasks: darwin.yml
  when: ansible_os_family == "Darwin"

- name: update current settings
  template:
    src: "gitconfig.j2"
    dest: "{{ home }}/.gitconfig"
    backup: yes
