---
- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: darwin.yml
  when: ansible_os_family == "Darwin"

- name: update current git settings
  template:
    src: "gitconfig.j2"
    dest: "{{ home }}/.gitconfig"
    backup: true
