---
- name: Install Ghostty and related tools on macOS
  include_tasks: darwin.yml
  when: ansible_os_family == 'Darwin'

- name: Install Ghostty and related tools on Debian
  include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Ensure Ghostty config directory exists
  file:
    path: "{{ ghostty_config_dir }}"
    state: directory
    mode: 0755

- name: Update Ghostty config file from template
  template:
    src: "config.j2"
    dest: "{{ ghostty_config_file }}"
    mode: 0644
    backup: true
