---
- import_tasks: "{{ playbook_dir }}/roles/asdf/tasks/add.yml"
  vars:
    plugins: "{{ plugins }}"

- import_tasks: "{{ playbook_dir }}/roles/asdf/tasks/install.yml"
  vars:
    plugins: "{{ plugins }}"

- import_tasks: "{{ playbook_dir }}/roles/asdf/tasks/global.yml"
  vars:
    plugins: "{{ plugins }}"
