---
- name: define variables
  set_fact:
    plugins:
      - name: "tmux"
        versions: ["3.3a"]
        global: "3.3a"

- name: install dependencies
  become: true
  apt:
    name:
      - wl-clipboard
    state: latest

- import_role:
    name: asdf
    tasks_from: add
  vars:
    plugins: "{{ plugins }}"

- import_role:
    name: asdf
    tasks_from: install
  vars:
    plugins: "{{ plugins }}"

- import_role:
    name: asdf
    tasks_from: global
  vars:
    plugins: "{{ plugins }}"
