---
- name: Define variables
  set_fact:
    plugins:
      - name: "tmux"
        versions: ["3.3a"]
        global: "3.3a"

- name: Install dependencies
  become: true
  apt:
    name:
      - wl-clipboard
    state: latest
    lock_timeout: 300

- import_tasks: "{{ playbook_dir }}/roles/asdf/tasks/plugin/add.yml"
  vars:
    plugins: "{{ plugins }}"

- import_tasks: "{{ playbook_dir }}/roles/asdf/tasks/plugin/install.yml"
  vars:
    plugins: "{{ plugins }}"

- import_tasks: "{{ playbook_dir }}/roles/asdf/tasks/plugin/global.yml"
  vars:
    plugins: "{{ plugins }}"
