- name: Add plugins
  command: "asdf plugin add {{ item.name }}"
  with_items:
    - { name: tmux }

- name: Install plugins
  command: "asdf install {{ item.name }} {{ item.version }}"
  with_items:
    - { name: tmux, version: latest }

- name: Setting plugins as global
  command: "asdf global {{ item.name }} {{ item.version }}"
  with_items:
    - { name: tmux, version: latest }

- name: Install tpm
  git:
    repo: "git@github.com:tmux-plugins/tpm.git"
    dest: "{{ home }}/.tmux/plugins/tpm"

- name: Checking if there is any existing configuration
  stat: 
    path: "{{ home }}/.tmux.conf"
  register: tmux

- name: Backing up
  command: "mv {{ home }}/.tmux.conf {{ home }}/.tmux.bak"
  when: tmux.stat.exists

- name: Adding settings
  copy:
    src: "{{ role_path }}/files/{{ item.file }}"
    dest: "{{ home }}/.{{ item.file }}"
  loop:
    - { file: "tmux.conf" }
