---
- name: Install tmux plugins using ASDF
  block:
    - name: Set ASDF plugin variables for {{ item.name }}
      set_fact:
        plugin_name: "{{ item.name }}"
        plugin_version: "{{ item.version }}"
        plugin_global: "{{ item.global | default(true) }}"
      
    - name: Manage plugin {{ plugin_name }} version {{ plugin_version }}
      include_tasks: "{{ playbook_dir }}/roles/asdf/tasks/manage-plugin.yml"
  
  loop: "{{ tmux_asdf_plugins }}"
  loop_control:
    label: "{{ item.name }} {{ item.version }}"

- name: Clone tmux plugin manager repository
  git:
    repo: "https://github.com/tmux-plugins/tpm.git"
    dest: "{{ home }}/.tmux/plugins/tpm"
    clone: true

- name: Copy .tmux.conf template to user's home directory
  template:
    src: "config.j2"
    dest: "{{ home }}/.tmux.conf"
    mode: 0644
    backup: true
