---
- name: Install tmux and related tools on macOS
  include_tasks: darwin.yml
  when: ansible_os_family == 'Darwin'

- name: Install tmux and related tools on Debian
  include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Clone tmux plugin manager repository
  git:
    repo: "https://github.com/tmux-plugins/tpm.git"
    dest: "{{ home }}/.tmux/plugins/tpm"
    clone: true

- name: Copy .tmux.conf template to user's home directory
  template:
    src: "{{ role_path }}/files/tmux_config.j2"
    dest: "{{ home }}/.tmux.conf"
    mode: 0644
    backup: true
