- name: Add plugins
  command: "asdf plugin add {{ item.name }}"
  with_items:
    - { name: tmux }

- name: Install plugins
  command: "asdf install {{ item.name }} {{ item.version }}"
  with_items:
    - { name: tmux, version: latest }

- name: Setting plugins as global
  command: "asdf global {{ item.name }} {{ item.version }}"
  with_items:
    - { name: tmux, version: latest }
