---
- name: Install dependencies
  homebrew:
    name: tmux
    state: latest

- name: Install TPM
  git:
    repo: "https://github.com/tmux-plugins/tpm.git"
    dest: "{{ home }}/.tmux/plugins/tpm"

- name: Update current settings
  copy:
    src: "{{ role_path }}/files/tmux.conf"
    dest: "{{ home }}/.tmux.conf"
    backup: true
