---
- name: Install tmux plugin
  include_tasks: "{{ playbook_dir }}/roles/asdf/tasks/manage-plugin.yml"
  vars:
    plugin_name: "tmux"
    plugin_version: "3.4"
    plugin_global: true

- name: Clone tmux plugin manager repository
  git:
    repo: "https://github.com/tmux-plugins/tpm.git"
    dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
    clone: true

- name: Copy .tmux.conf template to user's home directory
  template:
    src: "config.j2"
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
    mode: 0644
    backup: true
