---
- name: install dependencies
  homebrew:
    name:
      - yarn
      - gh
      - pnpm
    state: latest

- name: Install nvm
  shell:
    cmd: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
    executable: /bin/bash
  args:
    creates: "{{ home }}/.nvm/nvm.sh"

- name: install nodejs
  shell:
    cmd: source {{ home }}/.nvm/nvm.sh && nvm install {{ item }}
    executable: /bin/bash
  with_items:
   - lts/gallium
   - lts/hydrogen
