---
- name: Include Homebrew installation tasks
  include_tasks: ../../common/tasks/homebrew/install.yml

- name: Install plugins
  homebrew:
    name: "{{ item }}"
    state: latest
  loop:
    - yarn
    - gh

- name: Install NVM using the official script
  shell: "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash"
  args:
    executable: /bin/bash

- name: Install Node using NVM
  shell: |
    source {{ ansible_env.HOME }}/.nvm/nvm.sh
    nvm install 20.13.1
    nvm use 20.13.1
    nvm alias default 20.13.1
  args:
    executable: /bin/bash
