---
- name: install dependencies
  homebrew:
    name:
      - nvm
      - yarn
      - gh
      - pnpm
    state: latest

- name: retrieve install path
  command: brew --prefix nvm
  register: brew

- name: install nodejs
  shell:
    cmd: source {{ brew.stdout }}/nvm.sh && nvm install {{ item }}
    executable: /bin/bash
  with_items:
   - lts/argon
   - lts/boron
   - lts/carbon
   - lts/dubnium
   - lts/erbium
   - lts/fermium
   - lts/gallium
   - lts/hydrogen
