---
- name: define variables
  set_fact:
    plugins:
      - name: "nodejs"
        versions: ["lts-argon", "lts-boron", "lts-carbon", "lts-dubnium", "lts-erbium", "lts-fermium", "lts-gallium", "lts-hydrogen"]
        global: "lts-hydrogen"

      - name: "yarn"
        versions: ["1.22.19"]
        global: "1.22.19"

      - name: "github-cli"
        versions: ["2.28.0"]
        global: "2.28.0"

      - name: "pnpm"
        versions: ["8.4.0"]
        global: "8.4.0"

- import_tasks: "{{ playbook_dir }}/roles/asdf/tasks/plugin/add.yml"
  vars:
    plugins: "{{ plugins }}"

- import_tasks: "{{ playbook_dir }}/roles/asdf/tasks/plugin/install.yml"
  vars:
    plugins: "{{ plugins }}"

- import_tasks: "{{ playbook_dir }}/roles/asdf/tasks/plugin/global.yml"
  vars:
    plugins: "{{ plugins }}"
