---
- name: Define variables
  set_fact:
    plugins:
      - name: "nodejs"
        versions: ["16.14.0"]
        global: "16.14.0"

      - name: "yarn"
        versions: ["1.22.17"]
        global: "1.22.17"

      - name: "github-cli"
        versions: ["2.12.1"]
        global: "2.12.1"

      - name: "pnpm"
        versions: ["7.1.9"]
        global: "7.1.9"

- import_tasks: "{{ playbook_dir }}/roles/asdf/tasks/plugin/add.yml"
  vars:
    plugins: "{{ plugins }}"

- import_tasks: "{{ playbook_dir }}/roles/asdf/tasks/plugin/install.yml"
  vars:
    plugins: "{{ plugins }}"

- import_tasks: "{{ playbook_dir }}/roles/asdf/tasks/plugin/global.yml"
  vars:
    plugins: "{{ plugins }}"
