---
- name: Set plugin variables for Node.js, Yarn, and GitHub CLI
  set_fact:
    asdf_plugins:
      - name: "nodejs"
        version: "20.13.1"
      - name: "yarn"
        version: "1.22.22"
      - name: "github-cli"
        version: "2.49.2"

- name: Add plugins
  include_tasks: "{{ playbook_dir }}/roles/common/tasks/asdf/add-plugin.yml"
  vars:
    plugin_name: "{{ item.name }}"
    plugin_version: "{{ item.version }}"
  with_items: "{{ asdf_plugins }}"
  loop_control:
    loop_var: "item"

- name: Install plugins
  include_tasks: "{{ playbook_dir }}/roles/common/tasks/asdf/install-plugin.yml"
  vars:
    plugin_name: "{{ item.name }}"
    plugin_version: "{{ item.version }}"
  with_items: "{{ asdf_plugins }}"
  loop_control:
    loop_var: "item"

- name: Set global plugin versions
  include_tasks: "{{ playbook_dir }}/roles/common/tasks/asdf/global-plugin.yml"
  vars:
    plugin_name: "{{ item.name }}"
    plugin_version: "{{ item.version }}"
  with_items: "{{ asdf_plugins }}"
  loop_control:
    loop_var: "item"
