---
- name: Install Node plugin
  include_tasks: "{{ playbook_dir }}/roles/asdf/tasks/manage-plugin.yml"
  vars:
    plugin_name: "nodejs"
    plugin_version: "20.13.1"
    plugin_global: true

- name: Install Yarn plugin
  include_tasks: "{{ playbook_dir }}/roles/asdf/tasks/manage-plugin.yml"
  vars:
    plugin_name: "yarn"
    plugin_version: "1.22.22"
    plugin_global: true

- name: Install GitHub CLI plugin
  include_tasks: "{{ playbook_dir }}/roles/asdf/tasks/manage-plugin.yml"
  vars:
    plugin_name: "github-cli"
    plugin_version: "2.49.2"
    plugin_global: true

- name: Install PnpM plugin
  include_tasks: "{{ playbook_dir }}/roles/asdf/tasks/manage-plugin.yml"
  vars:
    plugin_name: "pnpm"
    plugin_version: "10.6.1"
    plugin_global: true
