---
- name: Add plugins
  command: "asdf plugin add {{ item.name }}"
  with_items:
    - { name: nodejs }
    - { name: yarn }
    - { name: github-cli }
  register: output
  failed_when: output.rc == 1

- name: Install plugins
  command: "asdf install {{ item.name }} {{ item.version }}"
  with_items:
    - { name: nodejs, version: "{{ asdf.versions.nodejs }}" }
    - { name: yarn, version: "{{ asdf.versions.yarn }}" }
    - { name: github-cli, version: "{{ asdf.versions.github-cli }}" }

- name: Setting plugins as global
  command: "asdf global {{ item.name }} {{ item.version }}"
  with_items:
    - { name: nodejs, version: "{{ asdf.versions.nodejs }}" }
    - { name: yarn, version: "{{ asdf.versions.yarn }}" }
    - { name: github-cli, version: "{{ asdf.versions.github-cli }}" }
