---
- name: Adding plugins
  shell: >-
    {{ asdf.execute_command }} &&
    asdf plugin add {{ item.name }}
  args:
    executable: "{{ asdf.shell }}"
    creates: "{{ asdf.path }}/plugins/{{ item.name }}"
    chdir: "{{ asdf.path }}"
  with_items:
    - { name: nodejs }
    - { name: yarn }
    - { name: github-cli }
  ignore_errors: True

- name: Installing plugins
  shell: >-
    {{ asdf.execute_command }} &&
    asdf install {{ item.name }} {{ item.version }}
  args:
    executable: "{{ asdf.shell }}"
    creates: "{{ asdf.path }}/installs/{{ item.name }}/{{ item.version }}"
    chdir: "{{ asdf.path }}"
  with_items:
    - { name: nodejs, version: 14.18.0 }
    - { name: yarn, version: 1.22.15 }
    - { name: github-cli, version: 2.0.0 }

- name: Setting plugins as global
  shell: >-
    {{ asdf.execute_command }} &&
    asdf global {{ item.name }} {{ item.version }}
  args:
    executable: "{{ asdf.shell }}"
    chdir: "{{ asdf.path }}"
  with_items:
    - { name: nodejs, version: 14.18.0 }
    - { name: yarn, version: 1.22.15 }
    - { name: github-cli, version: 2.0.0 }
