---
- name: install dependencies
  become: true
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    install_recommends: no
    cache_valid_time: 86400

- name: add repository key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: add apt repository
  become: true
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
    filename: docker

- name: install docker
  become: true
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    install_recommends: no
    cache_valid_time: 86400

- name: ensure group "docker" exists
  group:
    name: docker
    state: present

- name: add existing user '{{ user }}' to group sudo
  become: true
  user:
    name: '{{ user }}'
    groups: docker
    append: true

- name: install docker compose
  become: true
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.6.0/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755
