export LC_ALL=en_US.UTF-8

alias vim="nvim"
alias vi="nvim"

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH" # Yarn

export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools

export NVM_AUTO_USE=true  # Automatically load according .nvmrc

# Auto install zplug
if [[ ! -d ~/.zplug ]]; then
  git clone https://github.com/zplug/zplug ~/.zplug
  source ~/.zplug/init.zsh && zplug update --self
fi

source ~/.zplug/init.zsh

# Themes
zplug "sindresorhus/pure", use:"pure.zsh", from:"github", as:"theme"

# Plugins
zplug "lib/history", from:"oh-my-zsh"
zplug "lib/theme-and-appearance", from:"oh-my-zsh"
zplug "plugins/git", from:"oh-my-zsh"
zplug "plugins/fzf", from:"oh-my-zsh"
zplug "plugins/docker", from:"oh-my-zsh"
zplug "plugins/docker-compose", from:"oh-my-zsh"
zplug "mafredri/zsh-async"
zplug "lukechilds/zsh-nvm"
zplug "laurenkt/zsh-vimto"
zplug "zsh-users/zsh-syntax-highlighting"
zplug "zsh-users/zsh-autosuggestions"

# Installs packages that have not been installed yet
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    else
        echo
    fi
fi

# Runs zplug
zplug load

bindkey '^ ' autosuggest-accept # Use Ctrl+Space to select the current suggestion
bindkey '^P' up-history         # Shows history content above
bindkey '^N' down-history       # Shows history content below
