export LC_ALL=en_US.UTF-8

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH" # Yarn
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh                                          # FZF

export NVM_LAZY_LOAD=true # Lazy loading
export NVM_NO_USE=true    # Don't autoload node
export NVM_AUTO_USE=true  # Automatically load according .nvmrc

# Auto install zplug
if [[ ! -d ~/.zplug ]]; then
  git clone https://github.com/zplug/zplug ~/.zplug
  source ~/.zplug/init.zsh && zplug update --self
fi

source ~/.zplug/init.zsh

# Plugins
zplug mafredri/zsh-async, from:github
zplug ohmyzsh/ohmyzsh, use:lib/history.zsh
zplug zsh-users/zsh-syntax-highlighting
zplug zsh-users/zsh-autosuggestions
zplug lukechilds/zsh-nvm

# Themes
zplug sindresorhus/pure, use:pure.zsh, from:github, as:theme

# Installs packages that have not been installed yet
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    else
        echo
    fi
fi

# Runs zplug
zplug load

bindkey '^ ' autosuggest-accept # Use Ctrl+Space to select the current suggestion
