---
- name: Ensure GPG and pinentry-mac are installed
  homebrew:
    name: "{{ item }}"
    state: latest
  loop:
    - gpg
    - pinentry-mac

- name: Link gnupg if needed
  command: "brew link --overwrite gnupg"
  changed_when: false
  ignore_errors: true

- name: Get the path to pinentry-mac
  command: "which pinentry-mac"
  register: pinentry_path
  failed_when: pinentry_path.rc != 0
  changed_when: false 
