---
- name: Ensure GPG and pinentry-gnome are installed
  apt:
    name:
      - gnupg
      - pinentry-gnome3
    state: present
  become: true

- name: Get the path to pinentry-gnome3
  command: "which {{ gpg_pinentry_debian }}"
  register: pinentry_path
  changed_when: false
  failed_when: pinentry_path.rc != 0 
