---
- name: Install dependencies
  homebrew:
    name: 
      - gpg
      - pinentry
    state: latest

- name: Define Pinentry Program
  shell: echo "pinentry-program $(brew --prefix)/bin/pinentry" | tee ~/.gnupg/gpg-agent.conf
