---
- name: Check if GPG is installed
  command: gpg --version
  register: gpg_installed
  changed_when: false
  failed_when: false

- name: Install GPG and related tools on macOS
  include_tasks: darwin.yml
  when: ansible_os_family == 'Darwin'

- name: Install GPG and related tools on Debian
  include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Perform common GPG configuration tasks
  include_tasks: common.yml
  when: gpg_installed.rc == 0 or (ansible_os_family in ['Darwin', 'Debian'])
