---
- name: Install GPG and related tools on macOS
  include_tasks: darwin.yml
  when: ansible_os_family == 'Darwin'

- name: Install GPG and related tools on Debian
  include_tasks: debian.yml
  when: ansible_os_family == 'Debian'

- name: Restart GPG agent
  shell: |
    gpgconf --kill gpg-agent
    gpgconf --launch gpg-agent
  args:
    executable: /bin/bash

- name: Import GPG key
  shell: |
    echo "{{ gpg_key }}" | gpg --batch --yes --import
  args:
    executable: /bin/bash

- name: Get the key ID
  shell: |
    gpg --list-keys --with-colons | awk -F: '/^fpr:/ {print $10}'
  register: gpg_key_id
  changed_when: false

- name: Set GPG key trust level to ultimate
  shell: "echo -e \"{{ gpg_key_id.stdout_lines[0] }}:6:\" | gpg --batch --yes --import-ownertrust"
  args:
    executable: /bin/bash
  when: gpg_key_id.stdout_lines | length > 0
