---
- name: Install Visual Studio Code
  homebrew_cask:
    name: visual-studio-{{ visual_studio_code_package }}
    state: present

- name: Create settings folder if it does not exist
  file:
    path: "{{ home }}/Library/Application Support/Code/User"
    state: directory
    mode: 0755

- name: Add VS Code settings
  template:
    src: "{{ role_path }}/files/settings.j2"
    dest: "{{ home }}/Library/Application Support/Code/User/settings.json"
    mode: 0644
    backup: true

- name: Check if VS Code binary exists
  stat:
    path: "/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code"
  register: vscode_bin

- name: Install VS Code extensions
  command: "'/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code' --install-extension {{ item }}"
  with_items: "{{ visual_studio_code_extensions }}"
  when: vscode_bin.stat.exists
