# List of plugins
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'Morantron/tmux-fingers'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tpm'

set -ga terminal-overrides ",xterm-256color:Tc" # Improve support to colors

# Change prefix to `Ctrl + a`
set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g base-index 1                # Start windows numbering at 1
set -g mouse on                    # Enable mouse
set -g renumber-windows on         # renumber windows when a window is closed
setw -g automatic-rename off       # rename window to reflect current program
setw -g pane-base-index 1          # Make pane numbering consistent with windows

run '~/.tmux/plugins/tpm/tpm'      # Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
