---
- name: Set plugin variables for Neovim
  set_fact:
    asdf_plugins:
      - name: "neovim"
        version: "0.10.0"
      - name: "ripgrep"
        version: "14.0.3"

- name: Install Neovim and dependencies via ASDF
  include_tasks: "{{ playbook_dir }}/roles/asdf/tasks/manage-plugin.yml"
  vars:
    plugin_name: "{{ item.name }}"
    plugin_version: "{{ item.version }}"
  with_items: "{{ neovim_asdf_plugins }}"
  loop_control:
    loop_var: "item"
