---
- name: install homebrew dependencies
  homebrew:
    name: 
      - neovim
      - tree-sitter
      - luajit
      - python3
      - ripgrep
    state: latest
  
- name: install python dependencies
  pip:
    name:
      - neovim
      - pynvim
