---
- name: Include Homebrew installation tasks
  include_tasks: ../../common/tasks/homebrew/install.yml

- name: Ensure neovim and ripgrep are installed
  homebrew:
    name: "{{ item }}"
    state: latest
  loop:
    - neovim
    - ripgrep
