---
- name: Install build dependencies for Neovim on Debian
  apt:
    name: "{{ neovim_debian_dependencies }}"
    state: present
  become: true

- name: Include common Neovim installation tasks
  include_tasks: common.yml 
