---
- name: install apt dependencies
  become: true
  apt:
    name:
      - python3
      - python3-pip
      - ripgrep
      - luajit
    state: latest

- name: install python dependencies
  pip:
    name:
      - neovim

- name: define variables
  set_fact:
    plugins:
      - name: "neovim"
        versions: ["0.9.1"]
        global: "0.9.1"

- import_role:
    name: asdf
    tasks_from: add
  vars:
    plugins: "{{ plugins }}"

- import_role:
    name: asdf
    tasks_from: install
  vars:
    plugins: "{{ plugins }}"

- import_role:
    name: asdf
    tasks_from: global
  vars:
    plugins: "{{ plugins }}"
