---
- name: Add plugins
  command: "asdf plugin add {{ item.name }}"
  with_items:
    - { name: neovim }
    - { name: ripgrep }
  register: output
  failed_when: output.rc == 1

- name: Install plugins
  command: "asdf install {{ item.name }} {{ item.version }}"
  with_items:
    - { name: neovim, version: latest }
    - { name: ripgrep, version: latest }

- name: Setting plugins as global
  command: "asdf global {{ item.name }} {{ item.version }}"
  with_items:
    - { name: neovim, version: latest }
    - { name: ripgrep, version: latest }

- name: Checking if there is any existing configuration
  stat: 
    path: "{{ home }}/.config/nvim"
  register: neovim

- name: Backing up if there is already a configuration
  command: "mv {{ home }}/.config/nvim {{ home }}/.config/nvim-{{ ansible_date_time.iso8601 }}"
  when: neovim.stat.exists

- name: Creating root folder
  file:
    path: "{{ home }}/.config/nvim"
    state: directory

- name: Adding settings
  copy:
    src: "{{ role_path }}/files/{{ item.file }}"
    dest: "{{ home }}/.config/nvim/{{ item.file }}"
  loop:
    - { file: "init.vim" }
    - { file: "coc-settings.json" }
