---
- name: Set ASDF plugin variables
  set_fact:
    plugin_name: bat
    plugin_version: "{{ bat_version }}"

- name: Manage BAT plugin with ASDF
  include_tasks: "{{ playbook_dir }}/roles/asdf/tasks/manage-plugin.yml"
