---
- name: install dependencies
  homebrew_tap:
    name: homebrew/cask-fonts

- name: install jetbrains mono
  homebrew:
    name: font-jetbrains-mono
    state: latest

- name: install jetbrains mono nerd font
  homebrew:
    name: font-jetbrains-mono-nerd-font
    state: latest
