---
- name: install dependencies
  homebrew_tap:
    name: homebrew/cask-fonts

- name: install jetbrains mono
  homebrew_cask:
    name: font-jetbrains-mono
    state: latest

- name: install jetbrains mono nerd font
  homebrew_cask:
    name: font-jetbrains-mono-nerd-font
    state: latest

- name: install meslo nerd font
  homebrew_cask:
    name: font-meslo-lg-nerd-font
    state: latest
