---
- name: Install JetBrains Mono Nerd Font on macOS
  include_tasks: darwin.yml
  when: ansible_os_family == 'Darwin'

- name: Install JetBrains Mono Nerd Font on Debian
  include_tasks: debian.yml
  when: ansible_os_family == 'Debian'
