---
- name: Install Nerd Fonts on macOS
  include_tasks: darwin.yml
  when: ansible_os_family == 'Darwin'

- name: Install Nerd Fonts on Debian
  include_tasks: debian.yml
  when: ansible_os_family == 'Debian'
